### PR TITLE
feat(Adds an onChangeComplete handler, which fires at the end of mous…

### PR DESCRIPTION
**Pull request by tjbo**
Adds an onChangeComplete callback

- When using a stateless component, using onChange will cause the component to fail because of the drag event, with onChangeComplete this allows this component to be used in a stateless component, or if you only want to know the last change the user actually made on mouseup

### CODE REVIEW

**Comment by tjallen** [comment]
Good stuff, thanks for your contribution @tjbo 

The latest release should be auto-published to NPM shortly after the merge.

**Comment by tjbo** [comment]
Thanks, and thanks for the great library.

**Comment by francois06** [comment]
Hello, 
I looking for the onChangeCompleted callback 
 but it seems your NPM auto-publisher did not work :/  the latest version on npm is still the 1.5.2. (and no onchangecomplete)

Thanks !

**Comment by tjallen** [comment]
Hi @francois06 

Thanks for the message, you're right. This seems to be a flaw with [semantic-release](https://github.com/semantic-release/semantic-release) that others have encountered ([example here](https://github.com/semantic-release/semantic-release/issues/216)) where changes are not always deemed worthy of publishing a new build (as the last change is just a single _feature_ -- typically the releases will include multiple _features_ or any number of _fixes_) and there's no built-in method of forcing a publish while sticking to the guidelines.

It seems I may have to update the documentation with a _fix_ tag to force a publish for now & make sure the onChangeComplete build is published, then file an issue to research an alternative to semantic-release.

I'll update this thread when I've filed the issue and/or the new build has been published.

**Comment by tjallen** [comment]
Latest builds have been published to NPM, currently @ 1.5.4

On the subject of manual patch bumps / forcing releases; for now I'm going to hold off on filing an issue, as I see the semantic-release repo has taken on a new maintainer in the past week. Hopefully there'll be some discussion or follow-up on the open issues that refer to the topic in the coming weeks/months.

**Comment by francois06** [comment]
@tjallen :+1:  Thank you !!

**Pull request merged**
