### PR TITLE
feat(react): Support React 16

### PR DESCRIPTION
**Pull request by jorrit**
* Update React 16 peerDependency
* Remove React DOM peerDependency (it is not used by production code)
* Update enzyme and tests
* Add command to run eslint

The actual source code is not altered as the tests and examples suggest it is already compatible with React 16.

Most other devDependencies are outdated too, but updating them was not necessary to add React 16 support.

### CODE REVIEW

**Comment by jorrit** [comment]
@tjallen I have fixed the testing issues that occurred with my original commit.

**Comment by jorrit** [comment]
Thanks!

**Comment by tjallen** [comment]
Great, thanks again @jorrit.

If I recall correctly feat* flags should trigger a package release by semantic-release. If there are any issues I believe they've implemented some config for custom commit analysis, so will look into that if the release doesn't happen again.

Cheers.

**Comment by jorrit** [comment]
@tjallen I think the fact that there is no release because of the failing tests. I think they fail because the dependencies are not understood by npm@2. Maybe change travis such that it installs npm@5?

**Comment by jorrit** [comment]
Also, maybe you could add some more Node versions to the travis config.

**Comment by tjallen** [comment]
I'll look into this later today, thanks :+1:

**Comment by tjallen** [comment]
Have updated CI to use node@8 and npm@5.

CI has completed and semantic-release has published v1.6.0

Thanks again for your contributions :)

**Pull request merged**
